#!/bin/sh
set -e -E -o pipefail -u

HTTP_PORT=${HTTP_PORT:-80}
HTTPS_PORT=${HTTPS_PORT:-443}
YUMREPOS_DIR=${YUMREPOS_DIR:-"$PWD"/../yumrepos}

CONTAINER=yumrepos
IMAGE=arne/yumrepos-on-centos7

docker stop $CONTAINER 2> /dev/null || :
docker rm $CONTAINER 2> /dev/null || :
docker run -it \
    -v "$PWD":/local \
    -w /local \
    -v "$YUMREPOS_DIR":/project/yumrepos \
    --rm \
    --security-opt seccomp=unconfined \
    --tmpfs /run \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -p $HTTP_PORT:80 \
    -p $HTTPS_PORT:443 \
    --name $CONTAINER \
    -h $CONTAINER \
    $IMAGE
